Added host scanner options

diff --git a/dsturb b/dsturb
--- a/dsturb
+++ b/dsturb
@@ -19,7 +19,7 @@
 #
 
 # Required packages for script to run
-REQUIREMENTS="arpspoof:dsniff macchanger tc:iproute dhclient:isc-dhcp-client ifconfig:net-tools nmap wget"
+REQUIREMENTS="arpspoof:dsniff macchanger tc:iproute dhclient:isc-dhcp-client ifconfig:net-tools nmap wget arp:net-tools arp-scan netdiscover"
 
 # Script version
 VERSION=$(cat /usr/share/dsturb/version)
@@ -170,6 +170,7 @@ func_help()
     echo -e "         -c  --connect                     Enable internet access on target"
     echo -e "         -d  --disconnect                  Disable internet access on target"
     echo -e "         -r  --randomize                   Randomize interface's MAC Address"
+    echo -e "         -s  --scanner                     Host scanner: nmap,arp-scan,netdiscover,arp"
     echo -e "         -e  --exclude   [IP,IP,IP,...]    Exclude the following IP Addresses"
     echo -e "         -L  --limit     [rate-limit]      Limit bandwith for target"
     echo -e "         -h  --help                        Display help"
@@ -401,10 +402,16 @@ func_scan_network()
 	# Print host length warning
 	[[ $CIDR -lt 22 ]] && echo -e "${CGrn}[${CBRed}!${CGrn}]${CYel} Large network detected, this scan may take minutes or hours${CClr}"
 
+    echo -e "${CGrn}[${CYel}*${CGrn}]${CYel} Host scanner: ${CGrn}$HOST_SCANNER${CYel}...${CClr}"
     echo -e "${CGrn}[${CYel}*${CGrn}]${CYel} Scanning network ${CGrn}$NETWORK${CYel}...${CClr}"
 
     # Scan all available IP Address in then network
-    SCAN_RESULT=$(nmap -sn $NETWORK | grep "for" | cut -d ' ' -f 5-)
+    case $HOST_SCANNER in
+        nmap)           SCAN_RESULT=$(nmap -sn $NETWORK | grep "for" | cut -d ' ' -f 5-);;
+        arp-scan)       SCAN_RESULT=$(arp-scan -g -N -r 1 -l -I $INTERFACE | awk '/.*:.*:.*:.*:.*:.*/{print $1}');;
+        netdiscover)    SCAN_RESULT=$(netdiscover -Pi $INTERFACE -r $NETWORK | awk '/.*:.*:.*:.*:.*:.*/{print $1}');;
+        arp)            SCAN_RESULT=$(arp -ni $INTERFACE  | awk '/.*:.*:.*:.*:.*:.*/{print $1}');;
+    esac
 
     # Exclude gateway IP and your own IP from the list
     for IP in $(echo "$GATEWAY $MY_IP")
@@ -481,19 +488,23 @@ func_start_attack()
         sysctl -q net.ipv4.ip_forward=0
     fi
 
-    echo -e "${CGrn}[${CYel}$(date '+%T')${CGrn}]${CGrn} Attack is running! ${CYel}Press ${CGrn}CTRL+C${CYel} to stop${CClr}"
-
     RESCANNING_DELAY=60
 
-    sleep 5
-
+    echo -e "${CGrn}[${CYel}$(date '+%T')${CGrn}]${CYel} Using host scanner: ${CGrn}$HOST_SCANNER${CClr}"
     echo -e "${CGrn}[${CYel}$(date '+%T')${CGrn}]${CYel} Rescanning targets every ${CGrn}$RESCANNING_DELAY${CYel} seconds${CClr}"
+    echo -e "${CGrn}[${CYel}$(date '+%T')${CGrn}]${CGrn} Attack is running! ${CYel}Press ${CGrn}CTRL+C${CYel} to stop${CClr}"
 
     # Loop and discover new targets
     while true
     do
         sleep $RESCANNING_DELAY  # Nmap scan can interfere with arpspoof, so don't do it too often
-        NEW_SCAN=$(nmap -sn $NETWORK --disable-arp-ping | grep "for" | cut -d ' ' -f 5-)
+
+        case $HOST_SCANNER in
+            nmap)           NEW_SCAN=$(nmap -sn $NETWORK --disable-arp-ping | grep "for" | cut -d ' ' -f 5-);;
+            arp-scan)       NEW_SCAN=$(arp-scan -g -N -r 1 -l -I $INTERFACE | awk '/.*:.*:.*:.*:.*:.*/{print $1}');;
+            netdiscover)    NEW_SCAN=$(netdiscover -Pi $INTERFACE -r $NETWORK | awk '/.*:.*:.*:.*:.*:.*/{print $1}');;
+            arp)            NEW_SCAN=$(arp -ni $INTERFACE  | awk '/.*:.*:.*:.*:.*:.*/{print $1}');;
+        esac
 
         while read -r RESULT
         do
@@ -608,6 +619,28 @@ start_interactive_mode()
 
     # Just turn to <gateway>/<cidr> format, not really important
 	NETWORK="$GATEWAY/$CIDR"
+
+    # Select Host Discovery method
+    while true
+    do
+        func_header
+
+        echo -e "${CGrn}[${CYel}?${CGrn}]${CYel} Select host scanner:\n"
+        echo -e "    ${CGrn}1${CYel}) Nmap          (${CGrn}most reliable${CYel}) (${CRed}slow on large network${CYel}) (${CGrn}default${CYel})"
+        echo -e "    ${CGrn}2${CYel}) Arp-scan      (${CGrn}faster${CYel})"
+        echo -e "    ${CGrn}3${CYel}) Netdiscover   (${CGrn}slightly faster${CYel})"
+        echo -e "    ${CGrn}4${CYel}) Arp table     (${CGrn}fastest${CYel}) (${CRed}not reliable${CYel})"
+        echo -ne "\n${CGrn}[${CYel}Select${CGrn}]${CYel}: "
+        read -n1 HOST_SCANNER_PROMPT
+
+        case $HOST_SCANNER_PROMPT in
+            1) HOST_SCANNER=nmap; break ;;
+            2) HOST_SCANNER=arp-scan; break ;;
+            3) HOST_SCANNER=netdiscover; break ;;
+            4) HOST_SCANNER=arp; break ;;
+            *) [[ -z $HOST_SCANNER_PROMPT ]] && HOST_SCANNER=nmap && break; echo -e "\n\n${CGrn}[${CBRed}!${CGrn}]${CYel} Invalid input!${CClr}"; sleep 2 ;;
+        esac
+    done
 
     # Scan the network
     func_scan_network
@@ -771,7 +804,7 @@ echo -e ""
 [[ -z $1 ]] && start_interactive_mode
 
 # Get all options
-OPTIONS=$(getopt -l "help,connect,disconnect,randomize,exclude:,limit:" -o "hcdre:L:" -a -- "$@")
+OPTIONS=$(getopt -l "help,connect,disconnect,randomize,scanner:,exclude:,limit:" -o "hcdrs:e:L:" -a -- "$@")
 eval set -- "$OPTIONS"
 
 # Loop each options and add a flag
@@ -780,6 +813,7 @@ do
     case $1 in
         -c|--connect) FORWARD_TRAFFIC=true ;;
         -d|--disconnect) FORWARD_TRAFFIC=false ;;
+        -s|--scanner)  shift; [[ -z $1 ]] && func_help && exit 1; HOST_SCANNER=$1;;
         -r|--randomize) RANDOMIZE_MAC=true ;;
         -e|--exclude) shift; [[ -z $1 ]] && func_help && exit 1; EXCLUDED_IP=$1;;
         -L|--limit) shift; [[ -z $1 ]] && func_help && exit 1; RATE_LIMIT=$1;;
@@ -792,6 +826,7 @@ done
 # Default values
 [[ -z $FORWARD_TRAFFIC ]] && FORWARD_TRAFFIC=true
 [[ -z $RANDOMIZE_MAC ]] && RANDOMIZE_MAC=false
+[[ -z $HOST_SCANNER ]] && HOST_SCANNER=nmap
 
 # Check for interface availability
 [[ ! -d /sys/class/net/$INTERFACE ]] && echo -e "\n${CGrn}[${CBRed}!${CGrn}]${CYel} Interface \"${CRed}$INTERFACE${CYel}\" doesn't exist!${CClr}\n" && exit 1
@@ -803,6 +838,8 @@ then
     func_help
     exit 1
 fi
+
+[[ $HOST_SCANNER != nmap && $HOST_SCANNER != arp-scan && $HOST_SCANNER != netdiscover && $HOST_SCANNER != arp ]] && func_help && exit 1
 
 # Loop through all IP Addresses to validate IP Address format
 [[ ! -z $EXCLUDED_IP ]] && EXCLUDED_IP=$(echo "$EXCLUDED_IP" | tr ',' ' ') && for IP in "$EXCLUDED_IP"
